artifact_location: file:///mnt/c/Users/mrozt/Documents/DataTalksClub/mlops-zoomcamp-course/02-experiment-tracking/running-mlflow-examples/mlruns/0
creation_time: 1685154135883
experiment_id: '0'
last_update_time: 1685154135883
lifecycle_stage: active
name: Default
